---
title: "Assignment 3"
author: "Abigail Beasley & Cole Harris"
date: "2025-03-14"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load libraries}
#install.packages("pastecs")
#install.packages("ggplot2")
#install.packages("tidyverse")


library(tidyverse)
library(pastecs)
library(dplyr)
library(ggplot2) 
```

```{r load data}
texts = read.csv('TextMessages.csv')

```

```{r, clean and restructure data}
texts$Group <- as.factor(texts$Group)

texts_long <- pivot_longer(texts,
                           cols = c(Baseline, Six_months),
                           names_to = 'time',
                           values_to = 'text_count')
```

```{r plot 1}
#Creates stratified boxplot of text messages Group and Time (Hint: Faceted box plot)
#Adding labels, theme, and faceting of time:
boxplot_texts <- ggplot(texts_long, aes (x = Group, y = text_count, fill = 
  Group)) + geom_boxplot() + labs(title = 
  "Distribution of Text Messages by Group and Time", x = "Group", y = 
  "Number of Text Messages") + scale_x_discrete(labels = 
  c('1' = 'Group 1', '2' = 'Group 2')) + theme_minimal() + facet_wrap(~time)

print(boxplot_texts)
#Interpretation of the ggplot
#Beginning at the Baseline data, both groups show a similar distribution of text
#messages. The median values are close with Group 2 having a slightly higher
#median, but there is no obvious significant different in central tendency. The
#IQR is similar, suggesting similar spread amongst the central 50% of the data
#and there are no clear outliers for either group. Moving to the Six Months
#comparison, both groups show a decrease in the median number of text messages
#with Group 2 still having a larger median. The difference between medians has
#significantly increase compared to Baseline. In terms of spread, Group 1
#appears to have a larger IQR with the central 50% if the data being more spread
#out compared to Group 2. There are several outliers within Group 1 and only two
#outliers in Group 2. Based on these observations, it appears that at Baseline,
#both distributions are relatively symmetrical but Group 1 becomes more variable
#and asymmetrical with time. However, Group 2 maintains symmetry and has values
#only slightly decrease when forwarding to the Six Months category.

```

```{r plot 2}
# Creates stratified bar charts of text messages Group and Time (Hint: Faceted Bar Charts).
baseline_barchart <- ggplot(texts_long, aes(x=Group, y=text_count)) +
  # adding bar that sums total texts for each group
  geom_bar(stat = "summary", fun = "sum", fill ='orange',color='black') +
  # adding labels
  labs(title='Text totals by Group and Time', y='Total Texts', x='Group') +
  # renaming x-axis labels for clarity
  scale_x_discrete(labels = c('1'= 'Group 1', '2' = 'Group 2')) +
  # adding a theme 
  theme_classic() +
  # splitting into two sets of bar charts based on time factor
  facet_wrap(~time)

baseline_barchart
```

```{r descriptive stats}
#Ensuring text_count is numeric:
is.numeric(texts_long$text_count)
#It is numeric.

#Descriptive statistics for text message by Time and Group:
desc_stats <- texts_long %>% group_by(time, Group) %>% 
summarise(statistics = list(round(stat.desc(text_count, basic = 
TRUE, norm = FALSE), 2))) %>% unnest_wider(statistics) %>% 
  select(time, Group, mean, median, std.dev, min, max)

#Convert to data frame to remove <fct> and <dbl> notations:
desc_stats<- as.data.frame(desc_stats)

#Results of the data
print(desc_stats)

#Interpretation of results:
#Starting with Group 1 under Baseline, the most notable statistics are the mean
#and median. These values are 64.84 for mean and 64 for median, implying that
#the data for Group 1 under Baseline is symmetrically distributed. There is
#moderate variation in the text message data as the standard deviation is 10.68,
#meaning most individuals sent approximately 65 texts with some deviating by
#approximately 11 texts. Lastly, the highest value was 85 and the lowest was 47
#showing a wide range of scores. Moving to Group 2 under Baseline, the mean is
#slightly higher than Group 1 at 65.60 with the median outputting at 65,
#suggesting that this data is also symmetrically distributed. Similar to Group
#1, the standard deviation is 10.84, indicating that there is moderate spread
#within the data. The minimum and maximum are slightly higher with scores
#ranging from 89 to 46.
#Forwarding to the groups under Six Months, for Group 1, the mean has decreased
#from 64.84 to 52.96. Furthermore, the median has also decreased from 64 to 58.
#Therefore, the data is no longer symmetrical and has become left-skewed. The
#standard deviation has increased from 10.68  to 16.33, which means that the data
#has become substantially more varied. Additionally, the range has widen with
#values starting at 9 and ending at 78, suggesting numerous outliers. Similar,
#Group 2 has a decrease in mean and median, but not as severe as Group 1. Under
#the Six Months category, the mean and median for Group 2 have been decreased to
#61.84 and 62. Based on these values, it appears that the data has maintained
#symmetry. Interestingly, the standard deviation has decreased from 10.84 to
#9.41, indicating that the data is less varied and participants in Group 2 were
#more consistent with texting over time. Lastly, the minimum and maximum values
#have changed to 46 and 79, demonstrating values similar to Baseline and showing
#stable texting habits.

```
